### ISSUE TITLE
[BUG] NRE if UnityExplorer was not installed.

### ISSUE THREAD

**Issue by LeBron666** [xiaoye97/DSP_LDBTool#1]
您好，更新到2.0.4后，进游戏右上角有红字。<br/>
![image](https://user-images.githubusercontent.com/37588010/150669827-ec5870d7-d377-4d0e-981b-0d6d74ddf661.png)

**Comment by limoka** [comment]
Thanks for report. Please note that I don't speak Chinese so If you can please use English.

**Comment by limoka** [comment]
Should be fixed in v2.0.5

**Comment by LeBron666** [comment]
Sure. Thanks a lot.
