### ISSUE TITLE
"Why am I not responding when I press I and R, and displaying the recipe and item's Proto?

### ISSUE THREAD

**Issue by mczz25** [xiaoye97/DSP_LDBTool#2]
I have installed RuntimeUnityEditor, and the log shows "Failed to initialize REPL environment - Operation is not supported on this platform." I am a newbie, can anyone tell me why?

**Comment by limoka** [comment]
First of all this repo is not for RuntimeUnityEditor. Second that tool is not intended for "newbie usage".
