### ISSUE TITLE
[BUG] - Issue with updated version

### ISSUE THREAD

**Issue by Wolphin5** [xiaoye97/DSP_LDBTool#4]
**Describe the bug**
On loading of the 0.10.28.20779, with the updated 3.0.0 version, getting an error.
(See Screenshot for error message)

**To Reproduce**
On load of the game, using r2modman, to launch as modified.
Have only BepInEx, DSPModSave currently enabled.
Error shows on login screen.

**Expected behavior**
No Error messages.

**Log files**
Please upload log file from BepInEx folder to help solve issue
(not sure where grab the log from)

**Screenshots**
![image](https://github.com/xiaoye97/DSP_LDBTool/assets/44385601/30590d6b-94ae-47b8-8b70-62fd62919604)

**Additional context**
Game updated overnight.  Did download the update when it was offered in r2modman.

**Comment by Wolphin5** [comment]
Has been advised that mod installed is lying about version or game files corrupt.
Tried unstalling mod and had no change.  Proceeding with game reinstall

**Comment by Wolphin5** [comment]
- confirmed mod files deleted when uninstalled.
- Confirmed mod redownloaded correctly.
- Rebooted my PC (Had a windows update pending)
- Checked log, and LDBTool 2.0.6 was being loaded.
- Manually downloaded from https://dsp.thunderstore.io/package/xiaoye97/LDBTool/3.0.0/ and replaced files manually
- Found packaged version is incorrect.

**Comment by limoka** [comment]
Should be fixed with 3.0.1
